version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"      # n8n akan diakses pada port 5678
    environment:
      # Host & Tunnel URL untuk webhook/public API
      - N8N_HOST=${N8N_HOST:lead-gen-form-production.up.railway.app}
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL:lead-gen-form-production.up.railway.app}

      # Auth (opsional tapi disarankan)
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:Atharion}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:akunkomputer1}

      # Timezone
      - GENERIC_TIMEZONE=Asia/Jakarta

    volumes:
      - n8n_data:/home/node/.n8n  # menyimpan data workflow dan credentials

volumes:
  n8n_data:
    driver: local
